IUmesFK/TP3_FPOO

- JuegoSnake/GameObject.pde
Se definió la clase GameObject con sus métodos y atributos.
> clase GameObject

- JuegoSnake/Animal.pde
Se definió la clase junto a sus atributos y sus métodos correspondientes
> Definición de la clase Animal

- JuegoSnake/Cabeza.pde
se agrego atributos y métodos en la clase cabeza
> Definicion de Clase Cabeza

- JuegoSnake/Time.pde
Se define la clase Time y el método get DeltaTime
> Creación clase time

- JuegoSnake/Pajaro.pde
Se definió la clase Pajaro junto a sus atributos y metodos heredados de la clase Animal
> Definición de la clase Pajaro

- JuegoSnake/Raton.pde
Se definió la clase Raton junto a sus atributos y metodos heredados de la clase Animal
> Definición de la clase Raton

- JuegoSnake/Hud.pde
- JuegoSnake/JuegoSnake.pde
se define la clase Hud, sus atributos y el método display()
> creación clase Hud

- JuegoSnake/Insecto.pde
Se definió la clase Insecto junto a sus atributos y metodos heredados de la clase Animal
> Definición de la clase Insecto

- JuegoSnake/Snake.pde
se agregaron atributos y metodos en la Clase
> Definicion de la clase Snake

- JuegoSnake/AnimalComido.pde
Se agregaron atributos y metodos en la
ListaAnimalComido
> Se definio ListaAnimalComido

- JuegoSnake/Cuerpo.pde
Se definió la creación de la clase cuerpo y su respectivo código.
> CreacionDeLaClaseCuerpo

- JuegoSnake/JuegoSnake.pde
se escribió el código para el funcionamiento del escenario y el Snake.
> Se definió la clase juego Snake

- JuegoSnake/Cabeza.pde
> Actualización de la clase cabeza

- JuegoSnake/Escenario.pde
- JuegoSnake/JuegoSnake.pde
se agregaron correcciones finales a l juegoSnake
> Correcciones-Finales

- JuegoTanque/JuegoTanque/Transform.pde
Codificación de la clase transform.
> Creación de la Clase Transform

- JuegoTanque/JuegoTanque/ImageComponent.pde
- JuegoTanque/JuegoTanque/Transform.pde
Codificación de la clase ImageComponent
> Creación de la clase ImageComponent

- JuegoTanque/JuegoTanque/Bala.pde
se creo la clase bala con sus atributos y métodos
> Creación del la clase bala

- JuegoTanque/JuegoTanque/Muro.pde
Este commit extra surgió por el error de no haber guardado los cambios del processing, por ende, el archivo pde se subió sin su código
> Definición de la clase Muro

- JuegoTanque/JuegoTanque/Escenario.pde
> Creación Clase Escenario

- JuegoTanque/JuegoTanque/GestorMurallas.pde
Se creó y se definió la clase GestorMurallas para que se pueda almacenar cada elemento de la clase Muro con sus respectivos valores en una lista
> Definición de la clase GestorMurallas

- JuegoTanque/JuegoTanque/Tanque.pde
se creo la clase tanque con sus atributos y métodos
> Creacion de la clase tanque

- JuegoTanque/JuegoTanque/Escenario.pde
- JuegoTanque/JuegoTanque/GestorMurallas.pde
- JuegoTanque/JuegoTanque/JuegoTanque.pde
- JuegoTanque/JuegoTanque/Muro.pde
- JuegoTanque/JuegoTanque/Tanque.pde
Se definió la clase principal, JuegoTanque, y se hicieron pequeñas modificaciones
> Actualización JuegoTanque

- JuegoTanque/JuegoTanque/Time.pde
> Creación de la clase Time
